USE [Conference]
GO

/****** Object:  Table [dbo].[TicketCRUD]    Script Date: 3/28/2018 12:35:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TicketCRUD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Day] [nchar](10) NOT NULL,
	[Price] [int] NOT NULL,
	[Capacity] [int] NOT NULL,
 CONSTRAINT [PK_TicketCRUD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

